# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10.2
xcode_project: vinted-ab-ios.xcodeproj
xcode_scheme: vinted-ab-ios
before_install:
  - carthage bootstrap --platform iOS --verbose
script:
  - xcodebuild clean build test -project vinted-ab-ios.xcodeproj -scheme vinted-ab-ios -destination 'platform=iOS Simulator,name=iPhone Xs'
